name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Read README.md
        id: readme
        uses: juliangruber/read-file-action@v1
        with:
          path: ./README.md
      - name: Use Cowsay
        uses: Code-Hex/neo-cowsay-action@v1
        with:
          message:  "${{ steps.readme.outputs.content }}"